import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {runCrawl,crawlStatus,sitemapEntries,SOURCES} from '../dist/server/crawler.js';

function database(){const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+file,'utf8'));const wrap=(sql,values=[])=>({bind:(...args)=>wrap(sql,args),first:async()=>db.prepare(sql).get(...values),all:async()=>({results:db.prepare(sql).all(...values)}),run:async()=>({meta:{changes:Number(db.prepare(sql).run(...values).changes)}})});return{prepare:wrap,batch:async stmts=>{const result=[];for(const s of stmts)result.push(await s.run());return result;},close:()=>db.close()};}
test('sitemap excludes untrusted domains and non-recipe pages',()=>{const map=sitemapEntries('<urlset><url><loc>https://www.kikkoman.co.jp/homecook/search/recipe/1/</loc></url><url><loc>https://evil.test/a</loc></url><url><loc>https://www.kikkoman.co.jp/company/</loc></url></urlset>',SOURCES[0]);assert.deepEqual(map.urls,['https://www.kikkoman.co.jp/homecook/search/recipe/1/']);const index=sitemapEntries('<sitemapindex><sitemap><loc>https://misc.delishkitchen.tv/sitemaps/sitemap1.xml.gz</loc></sitemap></sitemapindex>',SOURCES[1]);assert.equal(index.urls.length,1);});
test('bounded crawl persists recipes, records errors and avoids duplicate daily runs',async()=>{const db=database(),realFetch=globalThis.fetch;const calls=[];globalThis.fetch=async url=>{url=String(url);calls.push(url);if(url.endsWith('robots.txt'))return new Response('User-agent: *\nAllow: /');if(url.includes('sitemap')){const host=url.includes('kikkoman')?'www.kikkoman.co.jp':'delishkitchen.tv';const path=host.includes('kikkoman')?'/homecook/search/recipe/':'/recipes/';const xml='<urlset>'+Array.from({length:6},(_,i)=>`<url><loc>https://${host}${path}${i}/</loc></url>`).join('')+'</urlset>';return new Response(xml);}return new Response('<script type="application/ld+json">'+JSON.stringify({'@type':'Recipe',name:'試験用レシピ',recipeIngredient:['卵'],recipeInstructions:['加熱する']})+'</script>');};try{const report=await runCrawl(db);assert.equal(report.imported,8);const status=await crawlStatus(db);assert.equal(status.total,8);assert.equal(status.queued,4);const count=calls.length;assert.equal((await runCrawl(db)).status,'already_run');assert.equal(calls.length,count);assert.equal((await crawlStatus(db)).last.imported,8);}finally{globalThis.fetch=realFetch;db.close();}});
test('robots rejection prevents recipe requests and records zero imports',async()=>{const db=database(),realFetch=globalThis.fetch;const calls=[];globalThis.fetch=async url=>{calls.push(String(url));return new Response('User-agent: *\nDisallow: /');};try{const r=await runCrawl(db);assert.equal(r.status,'no_imports');assert.equal(r.imported,0);assert.ok(calls.every(url=>url.endsWith('robots.txt')));assert.equal((await crawlStatus(db)).last.status,'no_imports');}finally{globalThis.fetch=realFetch;db.close();}});
test('active lease excludes simultaneous runs',async()=>{const db=database();try{await db.prepare('INSERT INTO crawl_state (key,body,busy_until) VALUES (?,?,?)').bind('lock','{}',Date.now()+60000).run();assert.equal((await runCrawl(db)).status,'busy');}finally{db.close();}});
