import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../dist/server/index.js';
import {parseDraft,extractFile} from '../public/file-import.mjs';
import fs from 'node:fs';
const id='12345678-1234-4234-8234-123456789abc';
const draft={id,title:'私の鶏肉レシピ',minutes:20,servings:'2人分',author:'自分',description:'メモ',ingredients:['鶏肉 200g','しょうゆ 大さじ1'],steps:['切る','20分加熱する']};
function storage(){const rows=new Map(),files=new Map();const DB={prepare:sql=>({bind:(...args)=>({first:async()=>rows.has(args[0])?{body:rows.get(args[0])}:null,run:async()=>{if(rows.has(args[0]))return{meta:{changes:0}};rows.set(args[0],args[2]);return{meta:{changes:1}};}})})};const FILES={put:async(key,data)=>files.set(key,data),get:async key=>files.has(key)?{body:files.get(key)}:null,delete:async key=>files.delete(key)};return{DB,FILES,rows,files};}
const request=data=>new Request('https://example.test/api/entries',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://example.test'},body:JSON.stringify(data)});
test('manual recipes persist without web fetching and retries create one row',async()=>{const env=storage();const r=await worker.fetch(request(draft),env);assert.equal(r.status,200);const recipe=(await r.json()).recipe;assert.equal(recipe.site,'手入力');assert.deepEqual(recipe.steps,draft.steps);assert.equal(recipe.minutes,20);await worker.fetch(request(draft),env);assert.equal(env.rows.size,1);const res=await worker.fetch(request({...draft,id:crypto.randomUUID(),steps:[]}),env);assert.equal(res.status,400);assert.equal(env.rows.size,1);});
test('PDF uploads retain original bytes and downloadable attachment',async()=>{const env=storage(),bytes=fs.readFileSync('tests/fixtures/recipe.pdf');const form=new FormData();form.append('recipe',JSON.stringify(draft));form.append('file',new File([bytes],'レシピ.pdf',{type:'application/pdf'}));const res=await worker.fetch(new Request('https://example.test/api/entries',{method:'POST',headers:{Origin:'https://example.test'},body:form}),env);assert.equal(res.status,200);const recipe=(await res.json()).recipe;assert.equal(recipe.site,'ファイルから追加');assert.equal(env.files.size,1);const download=await worker.fetch(new Request('https://example.test/api/files/'+id),env);assert.equal(download.status,200);assert.match(download.headers.get('Content-Disposition'),/^attachment/);assert.deepEqual(new Uint8Array(await download.arrayBuffer()),new Uint8Array(bytes));});
test('invalid upload and cross-origin requests leave storage untouched',async()=>{const env=storage();const form=new FormData();form.append('recipe',JSON.stringify(draft));form.append('file',new File(['<script>'], 'not.pdf'));const bad=await worker.fetch(new Request('https://example.test/api/entries',{method:'POST',body:form}),env);assert.equal(bad.status,400);assert.equal(env.files.size,0);const req=request(draft);req.headers.set('Origin','https://evil.test');assert.equal((await worker.fetch(req,env)).status,403);assert.equal(env.rows.size,0);});
test('failed database save removes newly uploaded file',async()=>{const env=storage();env.DB={prepare:()=>({bind:()=>({first:async()=>null,run:async()=>{throw Error('unavailable');}})})};const form=new FormData();form.append('recipe',JSON.stringify(draft));form.append('file',new File(['recipe'],'recipe.txt'));assert.equal((await worker.fetch(new Request('https://example.test/api/entries',{method:'POST',body:form}),env)).status,400);assert.equal(env.files.size,0);});
test('Japanese and English headings yield editable fields without inventing ingredients',()=>{const r=parseDraft('照り焼き\n調理時間：20分\n分量：2人分\n材料\n鶏肉 200g\n作り方\n1. 切る\n2. 焼く');assert.deepEqual(r.ingredients,['鶏肉 200g']);assert.deepEqual(r.steps,['切る','焼く']);assert.equal(r.minutes,'20');assert.deepEqual(parseDraft('Recipe\nNo structured sections').ingredients,[]);});
test('real PDF, DOCX and text extraction keep recipe text',async()=>{for(const name of ['recipe.pdf','recipe.docx','recipe.txt']){if(name.endsWith('docx'))globalThis.mammoth=(await import('mammoth/mammoth.browser.js')).default;const file=new File([fs.readFileSync('tests/fixtures/'+name)],name);const text=await extractFile(file);assert.match(text,/Chicken 200g/);assert.match(text,/20 minutes/);}});
