import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {needsOcr,ocrScale} from '../public/ocr.mjs';
import {parseDraft,extractFile} from '../public/file-import.mjs';
test('OCR activates for scans and text headers, retaining normal text PDFs',()=>{assert.equal(needsOcr(''),true);assert.equal(needsOcr('Recipe book page 1',true),true);assert.equal(needsOcr('Ingredients Chicken 200g Cook for 20 minutes',false),false);assert.equal(needsOcr('Long recipe text '.repeat(30),true),false);assert.ok(ocrScale(5000,5000)**2*5000*5000<=4000001);});
test('OCR-spaced Japanese headings are normalized without altering ingredient quantities',()=>{const draft=parseDraft('鶏肉の照り焼き\n調 理 時 間：２０分\n【材 料】\n鶏肉 200g\nしょうゆ 大さじ１\n【作 り 方】\n1. 20分焼く');assert.equal(draft.minutes,'20');assert.deepEqual(draft.ingredients,['鶏肉 200g','しょうゆ 大さじ１']);assert.deepEqual(draft.steps,['20分焼く']);});
test('canceled extraction never changes a draft',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(()=>extractFile(new File(['recipe'],'recipe.txt'),()=>{},{signal:controller.signal}),{name:'AbortError'});});
test('scanned PDF renders before OCR and terminates its worker',async()=>{const {createCanvas}=await import('@napi-rs/canvas');let terminated=false;globalThis.document={createElement:type=>{assert.equal(type,'canvas');return createCanvas(1,1);}};globalThis.Tesseract={createWorker:async(languages,oem,options)=>{assert.equal(languages,'jpn+eng');assert.equal(options.workerBlobURL,false);return{recognize:async canvas=>{assert.ok(canvas.width>0);return{data:{text:'Chicken Recipe\nIngredients\nChicken 200g\nDirections\nCook for 20 minutes.'}};},terminate:async()=>{terminated=true;}};}};try{const file=new File([fs.readFileSync('tests/fixtures/scan.pdf')],'scan.pdf');const text=await extractFile(file);const draft=parseDraft(text);assert.deepEqual(draft.ingredients,['Chicken 200g']);assert.match(draft.steps[0],/20 minutes/);assert.ok(terminated);}finally{delete globalThis.document;delete globalThis.Tesseract;}});
