import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {pathToFileURL} from 'node:url';import {createCanvas,loadImage} from '@napi-rs/canvas';
import {extractFile} from '../public/file-import.mjs';import {photoBounds} from '../public/pdf-photo.mjs';import worker from '../dist/server/index.js';
const canvasDocument={createElement:()=>{const c=createCanvas(1,1);c.toBlob=cb=>cb(new Blob([c.toBuffer('image/jpeg')],{type:'image/jpeg'}));return c;}};
function storage(){const rows=new Map(),files=new Map();return{rows,files,DB:{prepare:()=>({bind:(...a)=>({first:async()=>rows.has(a[0])?{body:rows.get(a[0])}:null,run:async()=>{if(rows.has(a[0]))return{meta:{changes:0}};rows.set(a[0],a[2]);return{meta:{changes:1}};}})})},FILES:{put:async(k,b)=>files.set(k,b),get:async k=>files.has(k)?{body:files.get(k)}:null,delete:async k=>files.delete(k)}};}
let jpeg;
test('extracts completion photo, excluding avatar and smaller instruction photo without stream async iteration',async()=>{
 globalThis.document=canvasDocument;const descriptor=Object.getOwnPropertyDescriptor(ReadableStream.prototype,Symbol.asyncIterator);delete ReadableStream.prototype[Symbol.asyncIterator];
 try{let photo;await extractFile(new File([fs.readFileSync('tests/fixtures/photo-recipe.pdf')],'photo.pdf'),()=>{},{onPhoto:p=>photo=p});assert.ok(photo);assert.equal(photo.page,1);assert.equal(photo.width,500);assert.equal(photo.height,375);jpeg=photo.blob;const c=createCanvas(500,375);c.getContext('2d').drawImage(await loadImage(new Uint8Array(await jpeg.arrayBuffer())),0,0);const pixel=c.getContext('2d').getImageData(250,187,1,1).data;assert.ok(pixel[0]>180&&pixel[1]<80&&pixel[2]<80,'Selected finished dish image, not purple avatar or blue instruction photo');}
 finally{delete globalThis.document;Object.defineProperty(ReadableStream.prototype,Symbol.asyncIterator,descriptor);}
 const OPS={save:1,restore:2,transform:3,paintImageXObject:4};assert.equal(photoBounds({fnArray:[3,4],argsArray:[[600,0,0,800,0,0],[]]},OPS,{width:600,height:800,transform:[1,0,0,-1,0,800]}).length,0);
});
test('actual form previews and saves JPEG, and private image endpoint serves it after reopening',async()=>{
 globalThis.document=canvasDocument;const env=storage(),nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,disabled:false,files:[],focus(){},showModal(){},close(){},reset(){}});return nodes.get(id);};let saved;
 const context=vm.createContext({$:node,URL,crypto:globalThis.crypto,AbortController,File,FormData,document:{querySelector:()=>node('close')},setMode(){},notice(){},load:async()=>{},fetch:async(path,options)=>{const response=await worker.fetch(new Request('https://example.test'+path,{...options,headers:{Origin:'https://example.test'}}),env);saved=await response.clone().json();return response;}});
 const source=fs.readFileSync('public/entry.js','utf8').replaceAll("'/file-import.mjs'",JSON.stringify(pathToFileURL(process.cwd()+'/public/file-import.mjs').href));new vm.Script(source,{importModuleDynamically:vm.constants.USE_MAIN_CONTEXT_DEFAULT_LOADER}).runInContext(context);
 try{node('entry-file').files=[new File([fs.readFileSync('tests/fixtures/photo-recipe.pdf')],'photo.pdf')];await node('entry-file').onchange();assert.equal(node('entry-photo-panel').hidden,false);assert.match(node('entry-photo-preview').src,/^blob:/);assert.equal(node('entry-title').value,'Chicken Recipe');await node('entry-form').onsubmit({preventDefault(){}});assert.ok(saved.recipe.image.startsWith('/api/entry-images/'));assert.equal(env.files.size,2);const response=await worker.fetch(new Request('https://example.test'+saved.recipe.image),env);assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),'image/jpeg');assert.equal(response.headers.get('Cache-Control'),'no-store');const bytes=new Uint8Array(await response.arrayBuffer());assert.equal(bytes[0],255);assert.equal(bytes[1],216);assert.equal(node('entry-photo-panel').hidden,true);assert.equal((await worker.fetch(new Request('https://example.test/api/entry-images/'+crypto.randomUUID()),env)).status,404);}
 finally{delete globalThis.document;}
});
test('bad image is rejected and failed database save cleans PDF and photo',async()=>{
 const draft={id:crypto.randomUUID(),title:'Photo recipe',ingredients:['Chicken 200g'],steps:['Cook'],minutes:null};const request=photo=>{const f=new FormData();f.append('recipe',JSON.stringify(draft));f.append('file',new File([fs.readFileSync('tests/fixtures/photo-recipe.pdf')],'photo.pdf'));f.append('photo',photo,'photo.jpg');return new Request('https://example.test/api/entries',{method:'POST',body:f});};
 const env=storage();assert.equal((await worker.fetch(request(new Blob(['script'],{type:'image/jpeg'})),env)).status,400);assert.equal(env.files.size,0);
 env.DB={prepare:()=>({bind:()=>({first:async()=>null,run:async()=>{throw Error('unavailable');}})})};assert.equal((await worker.fetch(request(jpeg),env)).status,400);assert.equal(env.files.size,0);
});
