import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../dist/server/index.js';
import {splitTranslation,translateField} from '../dist/server/translation.js';
const recipe={title:'Recipe',description:'',servings:'2 servings',ingredients:['Chicken 200 g'],steps:['Heat to 180°C for 20 minutes.']};
const db={prepare:()=>({bind:()=>({first:async()=>({body:JSON.stringify(recipe)})})})};
test('UTF-8 segmentation keeps emoji, whitespace and every character',()=>{const text=('鶏肉😀 200g。Chicken 20 minutes.\n').repeat(70),parts=splitTranslation(text);assert.equal(parts.join(''),text);for(const p of parts)assert.ok(new TextEncoder().encode(p).length<=480);});
test('translated fields preserve recipe data and reject invalid input',async()=>{const original=globalThis.fetch;let called=0;globalThis.fetch=async url=>{called++;const u=new URL(url);assert.equal(u.hostname,'api.mymemory.translated.net');assert.equal(u.searchParams.get('q'),recipe.steps[0]);assert.equal(u.searchParams.get('langpair'),'en|ja');return Response.json({responseStatus:200,responseData:{translatedText:'180°Cで20分加熱します。'}});};try{const input={id:'r1',field:'steps',index:0,source:'en',target:'ja'};assert.equal((await translateField(input,db)).text,'180°Cで20分加熱します。');await translateField(input,db);assert.equal(called,1);assert.equal(recipe.steps[0],'Heat to 180°C for 20 minutes.');await assert.rejects(()=>translateField({...input,target:'xx'},db));await assert.rejects(()=>translateField({...input,index:-1},db));await assert.rejects(()=>translateField({...input,field:'url'},db));}finally{globalThis.fetch=original;}});
test('quota warning never becomes a translated ingredient',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({responseStatus:429,responseData:{translatedText:'WARNING'}});try{await assert.rejects(()=>translateField({id:'r1',field:'ingredients',index:0,source:'en',target:'ko'},db),/利用上限/);}finally{globalThis.fetch=original;}});
test('translation API retains same-origin and JSON restrictions',async()=>{const res=await worker.fetch(new Request('https://example.test/api/translate',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://evil.test'},body:'{}'}),{DB:db});assert.equal(res.status,403);});

test('browser translation sends no credentials and reports provider quota',async()=>{const fs=await import('node:fs'),vm=await import('node:vm');const context={TextEncoder,URLSearchParams,AbortSignal,Error,document:{createElement:()=>({set innerHTML(v){this.value=v;}})},fetch:async(url,options)=>{assert.equal(options.credentials,'omit');assert.equal(options.referrerPolicy,'no-referrer');return Response.json({responseStatus:200,responseData:{translatedText:'鶏肉'}});}};vm.runInNewContext(fs.readFileSync('public/translate.js','utf8'),context);assert.equal(await context.translateInBrowser('Chicken','en','ja'),'鶏肉');context.fetch=async()=>new Response('',{status:429});await assert.rejects(()=>context.translateInBrowser('Rice','en','ja'),/利用上限/);});
