import {runCrawl,crawlStatus} from './crawler.js';
export const SITES={'www.kurashiru.com':'クラシル','delishkitchen.tv':'DELISH KITCHEN','cookpad.com':'クックパッド','recipe.rakuten.co.jp':'楽天レシピ','www.kikkoman.co.jp':'キッコーマン','www.sirogohan.com':'白ごはん.com'};
const UA='RecipeHub/1.0 (personal recipe reader)';
export function validateUrl(value){let u;try{u=new URL(value);}catch{throw Error('レシピURLを入力してください。');}if(u.protocol!=='https:'||!SITES[u.hostname]||u.username||u.password||(u.port&&u.port!=='443'))throw Error('対応サイトのHTTPSレシピURLを入力してください。');u.hash='';return u.href;}
const clean=v=>String(v??'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim();
export function minutes(v){const m=String(v||'').match(/^P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$/);return m?Number(m[1]||0)*1440+Number(m[2]||0)*60+Number(m[3]||0)+(Number(m[4]||0)>0?1:0):null;}
function steps(v){if(Array.isArray(v))return v.flatMap(steps);if(v&&typeof v==='object')return steps(v.itemListElement||v.text||v.name||'');return typeof v==='string'?v.split(/\r?\n/).map(clean).filter(Boolean):[];}
function ingredients(v){if(v?.itemListElement)return ingredients(v.itemListElement);return(Array.isArray(v)?v:v?[v]:[]).map(x=>x&&typeof x==='object'?['value','unitText','unitCode','name'].filter(k=>x[k]!=null).map(k=>x[k]).join(' '):x).map(clean).filter(Boolean);}
function* nodes(v){if(Array.isArray(v)){for(const x of v)yield* nodes(x);}else if(v&&typeof v==='object'){const types=Array.isArray(v['@type'])?v['@type']:[v['@type']];if(types.some(t=>String(t).split('/').pop()==='Recipe'))yield v;for(const x of Object.values(v))if(x&&typeof x==='object')yield* nodes(x);}}
export async function parseRecipe(doc,url){let node;for(const match of doc.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi)){if(!/\btype\s*=\s*['"]application\/ld\+json(?:;[^'"]*)?['"]/i.test(match[1]))continue;try{node=[...nodes(JSON.parse(match[2]))].find(n=>n.name);if(node)break;}catch{}}if(!node)throw Error('このページからレシピ情報を取得できませんでした。元のページをご確認ください。');const n=node;let image=Array.isArray(n.image)?n.image[0]:n.image;if(image&&typeof image==='object')image=image.url||image.contentUrl;try{image=image?new URL(image,url).href:'';if(image&&!image.startsWith('https://'))image='';}catch{image='';}let total=minutes(n.totalTime);if(total===null){const p=minutes(n.prepTime),c=minutes(n.cookTime);if(p!==null||c!==null)total=(p||0)+(c||0);}const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(url));let author=n.author;author=Array.isArray(author)?author.map(a=>a?.name||a).join(' / '):author?.name||author;return{id:Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,20),url,title:clean(n.name),description:clean(n.description),image,site:SITES[new URL(url).hostname],minutes:total,servings:clean(Array.isArray(n.recipeYield)?n.recipeYield.join(' / '):n.recipeYield),author:clean(author),ingredients:ingredients(n.recipeIngredient),steps:steps(n.recipeInstructions)};}
export async function boundedText(response,limit=3000000){if(!response.body)return'';const reader=response.body.getReader();let bytes=0;const chunks=[];while(true){const {value,done}=await reader.read();if(done)break;bytes+=value.length;if(bytes>limit){await reader.cancel();throw Error('ページのサイズが大きすぎます。');}chunks.push(value);}const all=new Uint8Array(bytes);let at=0;for(const c of chunks){all.set(c,at);at+=c.length;}return new TextDecoder().decode(all);}
export async function fetchPage(url){for(let i=0;i<5;i++){const candidate=new URL(url);if(candidate.protocol==='https:'&&candidate.hostname==='misc.delishkitchen.tv'&&!candidate.username&&!candidate.password&&!candidate.port&&(candidate.pathname==='/robots.txt'||/^\/sitemaps\/[^/]+\.xml(?:\.gz)?$/.test(candidate.pathname))){url=candidate.href;}else{url=validateUrl(url);}const res=await fetch(url,{redirect:'manual',headers:{'User-Agent':UA},signal:AbortSignal.timeout(12000)});if(res.status>=300&&res.status<400){const target=res.headers.get('Location');await res.body?.cancel();if(!target)throw Error('移動先を取得できませんでした。');url=new URL(target,url).href;continue;}return res;}throw Error('ページの移動回数が多すぎます。');}
export function robotsAllowed(text,url){const groups=[];let g={agents:[],rules:[]},seen=false;for(const raw of text.split(/\r?\n/)){const line=raw.split('#')[0].trim(),i=line.indexOf(':');if(i<0)continue;const key=line.slice(0,i).toLowerCase(),v=line.slice(i+1).trim();if(key==='user-agent'){if(seen){groups.push(g);g={agents:[],rules:[]};seen=false;}g.agents.push(v.toLowerCase());}else if((key==='allow'||key==='disallow')&&g.agents.length){seen=true;if(v)g.rules.push({allow:key==='allow',path:v});}}groups.push(g);const specific=groups.filter(g=>g.agents.some(a=>a!=='*'&&UA.toLowerCase().startsWith(a))),selected=specific.length?specific:groups.filter(g=>g.agents.includes('*'));const path=new URL(url).pathname+new URL(url).search;let winner=null;for(const rule of selected.flatMap(g=>g.rules)){let pattern=rule.path.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*');if(pattern.endsWith('\\$'))pattern=pattern.slice(0,-2)+'$';if(new RegExp('^'+pattern).test(path)&&(!winner||rule.path.length>winner.path.length||(rule.path.length===winner.path.length&&rule.allow)))winner=rule;}return!winner||winner.allow;}
export async function importRecipe(url,db,robotsDocument){url=validateUrl(url);if(robotsDocument===undefined){const robots=await fetchPage(new URL('/robots.txt',url).href);if(robots.status!==404){if(!robots.ok)throw Error('サイトの取得可否を確認できませんでした。');robotsDocument=await boundedText(robots,500000);}}if(robotsDocument!==undefined&&!robotsAllowed(robotsDocument,url))throw Error('このページは自動取得が許可されていません。元のサイトをご覧ください。');const response=await fetchPage(url);if(!response.ok)throw Error('サイトからページを取得できませんでした。');const recipe=await parseRecipe(await boundedText(response),url);await db.prepare('INSERT INTO recipes (id,url,body,created) VALUES (?,?,?,?) ON CONFLICT(url) DO UPDATE SET body=excluded.body').bind(recipe.id,url,JSON.stringify(recipe),new Date().toISOString()).run();return recipe;}
const fold=s=>String(s).normalize('NFKC').toLowerCase();
async function searchRecipes(url,db){const {results}=await db.prepare('SELECT body FROM recipes ORDER BY created DESC').all();const q=fold(url.searchParams.get('q')||'').split(/\s+/).filter(Boolean),site=url.searchParams.get('site'),max=Number(url.searchParams.get('minutes')||0);const rows=results.map(r=>JSON.parse(r.body)).filter(r=>q.every(w=>fold([r.title,r.description,...r.ingredients].join(' ')).includes(w))&&(!site||r.site===site)&&(!max||(r.minutes!==null&&r.minutes<=max)));if(url.searchParams.get('sort')==='time')rows.sort((a,b)=>(a.minutes??Infinity)-(b.minutes??Infinity));return rows;}
async function webSearch(q,env){if(!env.BRAVE_SEARCH_API_KEY)throw Error('Web横断検索は未設定です。URLからの追加と登録済みレシピの検索は利用できます。');if(typeof q!=='string'||!q.trim()||q.length>150)throw Error('検索語を1〜150文字で入力してください。');const query=q+' レシピ ('+Object.keys(SITES).map(h=>'site:'+h).join(' OR ')+')';const endpoint='https://api.search.brave.com/res/v1/web/search?'+new URLSearchParams({q:query,count:'10',country:'JP',search_lang:'jp'});const res=await fetch(endpoint,{headers:{'X-Subscription-Token':env.BRAVE_SEARCH_API_KEY},signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error('検索サービスに接続できませんでした。');const data=JSON.parse(await boundedText(res));const urls=[];for(const r of data.web?.results||[]){try{const u=validateUrl(r.url);if(!urls.includes(u))urls.push(u);}catch{}}let imported=0;const skipped=[];for(const url of urls.slice(0,10)){try{await importRecipe(url,env.DB);imported++;}catch(e){skipped.push({url,reason:e.message});}}return{found:urls.length,imported,skipped};}
const security={'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; img-src 'self' https: data:; script-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...security,'Content-Type':'application/json;charset=utf-8','Cache-Control':'no-store'}});
export default{async fetch(request,env){const url=new URL(request.url);try{if(url.pathname.startsWith('/api/')){if(request.method==='GET'&&url.pathname==='/api/crawl/status')return json(await crawlStatus(env.DB));if(request.method==='GET'&&url.pathname==='/api/config')return json({sites:SITES,webSearch:Boolean(env.BRAVE_SEARCH_API_KEY)});if(request.method==='GET'&&url.pathname==='/api/recipes')return json({recipes:await searchRecipes(url,env.DB)});if(request.method!=='POST')return json({error:'見つかりません。'},404);if(request.headers.get('Origin')&&request.headers.get('Origin')!==url.origin)return json({error:'別サイトからの操作はできません。'},403);if(!request.headers.get('Content-Type')?.startsWith('application/json'))return json({error:'JSONを指定してください。'},415);const data=JSON.parse(await boundedText(request,8192));if(url.pathname==='/api/crawl/run')return json(await runCrawl(env.DB));if(url.pathname==='/api/import'){if(typeof data.url!=='string')throw Error('URLを入力してください。');return json({recipe:await importRecipe(data.url,env.DB)});}if(url.pathname==='/api/web-search')return json(await webSearch(data.q,env));return json({error:'見つかりません。'},404);}if(request.method!=='GET'&&request.method!=='HEAD')return new Response('Method not allowed',{status:405});const path=url.pathname==='/'?'/index.html':url.pathname;const asset=ASSETS[path];if(!asset)return new Response('Not found',{status:404});const types={html:'text/html;charset=utf-8',js:'text/javascript;charset=utf-8',css:'text/css;charset=utf-8',svg:'image/svg+xml',json:'application/json',webmanifest:'application/manifest+json',png:'image/png'};const headers={...security,'Content-Type':types[path.split('.').pop()]||'application/octet-stream','Cache-Control':'no-cache'};if(path==='/sw.js')headers['Service-Worker-Allowed']='/';const body=asset.binary?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body;return new Response(request.method==='HEAD'?null:body,{headers});}catch(e){console.error('Recipe Hub request failed',e.message);return json({error:e.message||'処理できませんでした。再度お試しください。'},400);}}};
